### ISSUE TITLE
forcing relay does not work in the code (at least for chrome, due to chrome implementation)

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/webrtc#4]
Related: https://bugs.chromium.org/p/webrtc/issues/detail?id=4869.

I would suggest using a shim to make it work.

**Comment by DoruM** [comment]
This issue is solved by the following type of code:

'''
if (event.candidate.candidate.indexOf("relay") > 0) {
                send({
                    type: "candidate",
                    candidate: event.candidate
                });
            }
'''

What the bug at  https://bugs.chromium.org/p/webrtc/issues/detail?id=4869 says is the following thing:

If within the configuration you have a json with the property "iceTransportPolicy": "relay", then it will only use turn servers (relay candidates). This is not implemented in Chrome and probably it never will, given the fact that the issue was noticed at least one year ago.

I don't think we can do much better than using that particular code.
